import { post, videoPost } from './http'

export const autoLogin = params => post('/tempuser/login', params)
export const userLogin = params => post('/user/login', params)
export const register = params => post('/user/reg', params)
export const payment = params => post('/order/confirm', params)
export const getDomain = params => post('/domain/get', params)
export const getRecommendCartoons = params => post('/recommend/lists', params)
export const getUserInfo = params => post('/user/info', params)
export const getCategory = params => post('/cartoonType/list', params)
export const getCartoons = params => post('/cartoon/lists', params)
export const getBulletin = params => post('/bulletin/list', params)
export const getBulletinDetail = params => post('/bulletin/selectById', params)
export const getPayMenu = params => post('/pay/pricelist', params)
export const getPayMenuTest = params => post('/pay/pricetest', params)
export const getPayList = params => post('/pay/newPayment', params)
export const getPayListTest = params => post('/pay/testPayment', params)
export const getHigh = params => post('/cartoon/rand', params) // 取高爆庫
export const getCartoonLastRead = params => post('/history/last', params)
export const getChapter = params => post('/chapter/chapterWithNext', params)
export const join = params => post('/history/join', params)
export const getMoreCartoons = params => post('/statiscartoon/minlist', params)
export const getHistoryCartoons = params => post('/history/lists', params)
export const getMyCartoons = params => post('/fav/list', params)
export const operatingMyCartoon = params => post('/fav/add', params)
export const deleteHistoryCartoon = params => post('/history/remove', params)
export const deleteAllHistoryCartoon = () => post('/history/removeAll')
export const getCartoonInfo = params => post('/cartoon/info', params)
export const getDirectory = params => post('/chapter/catalog', params)
export const search = params => post('/cartoon/search', params)
export const download = params => post('/index/download', params)
export const tradeRecord = params => post('tradeRecord/AllTradeRecordlists', params)
export const retrieveUser = params => post('/order/user', params)
export const resetPassword = params => post('/user/reset/password', params)
export const myRecommendInfo = () => post('/recommend/parent')
export const addRecommendId = params => post('/recommend/parent', params)
export const homeToBulletin = params => post('/event/advertising/latest', params)
export const userGiftInfo = () => post('/user/getGiftList')
export const receiveUserGift = params => post('/user/receiveGift', params)
export const getVideoLinkid = params => post('/config/videosharelinkid', params)
export const getBackBooks = () => post('/positionback/backUrlInfos')
export const getAdList = () => post('/dsp/list')
export const getCooperateList = () => post('/connectionInfo/getList')
export const checkDomain = () => post('/domain/checkDomain')
export const videoMaintainList = params => post('/publicchannel/hide', params)

// video
export const getVideos = params => videoPost('/list', params)
export const getRandomVideos = params => videoPost('/randomlist', params)
export const getVideoImgDomain = params => videoPost('/getVideoDomainType', params)
export const videoPlayer = params => videoPost('/player', params)
export const getTags = () => videoPost('/showtags')
export const getRankingTags = () => videoPost('/showtoptags')
export const analyticsByTag = params => videoPost('/analytics/tag', params)
export const getVideosByTag = params => videoPost('/catelist', params)
export const getMyVideos = params => videoPost('/listmyvideo', params)
export const getHistoryVideos = params => videoPost('/getplayhis', params)
export const deleteMyVideo = params => videoPost('/delmyvideo', params)
export const deleteHistoryVideo = params => videoPost('/delplayhist', params)
export const addMyVideo = params => videoPost('/addmyvideo', params)
export const searchVideo = params => videoPost('/search', params)
export const getKeywords = () => videoPost('/hot/getkeywords')
export const preview = () => videoPost('/preview')
